### PR TITLE
fix(rest): properly handle string-encoded well-known types in URLs

### LINKED ISSUE #1263: HttpJson UpdateUserRequest's FieldMask is unable to be Unmarshalled
Java Gapic-Generator is implementing showcase coverage for the Identity client (modeled after golang). Draft PR with the full sample code: https://github.com/googleapis/gapic-generator-java/pull/1431 

Relevant Code for the test case:
```
CreateUserRequest createUserRequest = CreateUserRequest.newBuilder()
            .setUser(User.newBuilder().setDisplayName("Jane Doe").setEmail("janedoe@example.com").setNickname("Doe").setHeightFeet(5).build()).build();
    User user = httpjsonClient.createUser(createUserRequest);
    User expected = createUserRequest.getUser();

    UpdateUserRequest updateUserRequest = UpdateUserRequest.newBuilder()
            .setUser(User.newBuilder()
                    .setName(user.getName())
                    .setDisplayName(user.getDisplayName())
                    .setEmail("janedoe@jane.com")
                    .setHeightFeet(6.0)
                    .setEnableNotifications(true)
                    .build())
            .setUpdateMask(FieldMask.newBuilder().addAllPaths(Arrays.asList("email", "height_feet", "enable_notifications")).build())
            .build();
    User updatedUser = httpjsonClient.updateUser(updateUserRequest);
```

Results in this error:
```
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
POST http://localhost:7469/v1beta1/users/1?updateMask=email,heightFeet,enableNotifications
{"error":{"code":400,"message":"error reading query params: terminal field \"updateMask\" of field path \"updateMask\" is of type \"message\" with value string \"email,heightFeet,enableNotifications\", which could not be parsed: unable to unmarshal field \"update_mask\" in message \"google.showcase.v1beta1.UpdateUserRequest\": proto: syntax error (line 1:1): invalid value email","details":null,"Body":"","Header":null,"Errors":null}}
```

Logging the HttpRequest:
```
-------------- REQUEST  --------------
POST http://localhost:7469/v1beta1/users/1?updateMask=email,heightFeet,enableNotifications
Accept-Encoding: gzip
User-Agent: Google-HTTP-Java-Client/1.43.0 (gzip)
x-http-method-override: PATCH
x-goog-api-client: gl-java/11.0.16.1 gapic/0.0.1-SHAPSHOT gax/2.23.3-SNAPSHOT rest/
Content-Type: application/json; charset=utf-8
Content-Length: 115

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'User-Agent: Google-HTTP-Java-Client/1.43.0 (gzip)' -H 'x-http-method-override: PATCH' -H 'x-goog-api-client: gl-java/11.0.16.1 gapic/0.0.1-SHAPSHOT gax/2.23.3-SNAPSHOT rest/' -H 'Content-Type: application/json; charset=utf-8' -d '@-' -- 'http://localhost:7469/v1beta1/users/12?updateMask=email,heightFeet,enableNotifications' << $$$
Total: 115 bytes
{"name":"users/12","displayName":"Jane Doe","email":"janedoe@jane.com","heightFeet":6.0,"enableNotifications":true}
```
The logs seems to show that the updateMask field is encodedproperly as a query param, but Showcase is unable to decode this query param:
```
2023/03/07 10:16:40 error reading query params: terminal field "updateMask" of field path "updateMask" is of type "message" with value string "email,heightFeet,enableNotifications", which could not be parsed: unable to unmarshal field "update_mask" in message "google.showcase.v1beta1.UpdateUserRequest": proto: syntax error (line 1:1): invalid value email
```

---
Thought this might be an error with Java's HttpJson implementation for FieldMask, but tested this with Java-Scheduler using HttpJson + FieldMask and this works properly. 

```
-------------- REQUEST  --------------
POST https://cloudscheduler.googleapis.com:443/v1/projects/lawrence-test-project-2/locations/us-central1/jobs/72824232043972625121?$alt=json;enum-encoding%3Dint&updateMask=schedule,timeZone
Accept-Encoding: gzip
Authorization: Bearer {BEARER}
User-Agent: Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-user-project: {PROJECT}
x-http-method-override: PATCH
x-goog-api-client: gl-java/11.0.16.1 gapic/2.11.0 gax/2.23.1 rest/
Content-Type: application/json
Content-Length: 330

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: Bearer {BEARER}' -H 'User-Agent: Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-user-project: lawrence-test-project-2' -H 'x-http-method-override: PATCH' -H 'x-goog-api-client: gl-java/11.0.16.1 gapic/2.11.0 gax/2.23.1 rest/' -H 'Content-Type: application/json' -d '@-' -- 'https://cloudscheduler.googleapis.com:443/v1/projects/{PROJECT}/locations/{LOCATION}/jobs/{ID}?$alt=json;enum-encoding%3Dint&updateMask=schedule,timeZone' << $$$
Total: 330 bytes
{"name":"projects/{PROJECT}/locations/{LOCATION}/jobs/{ID}","httpTarget":{"uri":"http://example.com/","httpMethod":2,"headers":{"User-Agent":"Google-Cloud-Scheduler"}},"userUpdateTime":"2023-03-07T15:57:34Z","state":1,"schedule":"1 10 * * FRI","timeZone":"America/New_York","attemptDeadline":"180s"}
```

### PR DESCRIPTION
**Pull request by vchudnov-g**
Well-known type messages that JSON-encode to strings appear in URL paths and query params unquoted. When we extract them from these places, we need to quote them to make them valid JSON that we can pass to the JSON deserializer. We weren't doing the quoting previously.

Fixes #1263

### CODE REVIEW

File: util/genrest/resttools/populatefield.go [hunk 1]
```diff
@@ -249,10 +262,15 @@ func parseWellKnownType(message protoreflect.Message, fieldDescriptor protorefle
...
 	fieldMsg := messageFieldTypes.Message(fieldDescriptor.Index())
 	fullName := string(fieldMsg.Descriptor().FullName())
-	if !wellKnownTypes[fullName] {
+	stringEncoded, isWellKnown := wellKnownTypes[fullName]
+	if !isWellKnown {
 		return nil, nil
 	}
 
+	if stringEncoded {
+		value = fmt.Sprintf(`"%s"`, value)
```
Comment (noahdietz) [inline util/genrest/resttools/populatefield.go:271]: Does using this work the same way or no?
```suggestion
		value = fmt.Sprintf("%q", value)
```

**Review by noahdietz — APPROVED** [review]
One question, but otherwise, makes sense. Thank you

File: util/genrest/resttools/populatefield.go (hunk 1 above)
Comment (vchudnov-g) [reply util/genrest/resttools/populatefield.go]: Oh, good catch. Thanks!

**Comment by noahdietz** [comment]
Oops, this doesn't work for Go: https://github.com/googleapis/gapic-generator-go/actions/runs/4669784400/jobs/8268694956?pr=1276

**Comment by noahdietz** [comment]
We probably need to test if it is already "quoted" before quoting it again via `%q`

**Comment by noahdietz** [comment]
#1294 should do it
